version: '2'
services:
  sqs:
    container_name: dev-sqs
    image: s12v/elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./src/main/resources/sqs/elasticmq.conf:/etc/elasticmq/elasticmq.conf